# Generated by Django 3.2.9 on 2025-07-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('roles', models.CharField(blank=True, default=',', help_text='Роли пользователя через запятую', max_length=2000, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('name', models.CharField(blank=True, help_text='Имя параметра', max_length=132, null=True, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='Описание параметра', verbose_name='Описание')),
                ('category', models.CharField(default='dflt', help_text='Категория параметра', max_length=256)),
                ('type', models.CharField(blank=True, default='str', help_text='Тип параметра', max_length=256, null=True)),
                ('value', models.TextField(default='', help_text='Значение параметра')),
                ('roles', models.CharField(blank=True, default=',', help_text='Роли через запятую, которые можно использовать с параметром', max_length=2000, null=True)),
                ('enabled', models.BooleanField(default=True, help_text='Включено')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Updates',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('update_id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('message', models.TextField(default='')),
                ('from_id', models.BigIntegerField(blank=True, null=True)),
                ('chat_id', models.BigIntegerField(default=0)),
                ('type', models.CharField(default='', max_length=256)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.CharField(blank=True, default=',', help_text='Роли пользователя через запятую', max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='users', to='users.GroupRoles'),
        ),
    ]
