# Generated by Django 3.2.9 on 2025-07-19 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20250718_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updates',
            name='type',
        ),
        migrations.AddField(
            model_name='updates',
            name='json',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='updates',
            name='chat_id',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
