# Generated by Django 3.2.9 on 2025-08-28 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_usersoptions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='updates',
            options={},
        ),
        migrations.AlterField(
            model_name='updates',
            name='chat_id',
            field=models.BigIntegerField(blank=True, db_index=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='updates',
            name='from_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='updates',
            name='message',
            field=models.TextField(blank=True, db_index=True, default='', null=True),
        ),
        migrations.AddIndex(
            model_name='updates',
            index=models.Index(fields=['from_id'], name='idx_from_id'),
        ),
        migrations.AddIndex(
            model_name='updates',
            index=models.Index(fields=['chat_id'], name='idx_chat_id'),
        ),
        migrations.AddIndex(
            model_name='updates',
            index=models.Index(fields=['message'], name='idx_message'),
        ),
    ]
