# Generated by Django 3.2.9 on 2026-02-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20250828_0833'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersoptions',
            options={},
        ),
        migrations.AlterField(
            model_name='usersoptions',
            name='name',
            field=models.CharField(blank=True, help_text='Имя параметра', max_length=250, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='usersoptions',
            unique_together={('user', 'name')},
        ),
    ]
