dynaconf_merge: true
default:
  ADMIN_IDS:
    - 1111111111
  ERRORS_CHAT_ID: -222222222
  ERRORS_THREAD_ID:
  UPDATES_PATH: "/updates"
  WEBHOOK_DOMAIN: "https://example.com"
  YAML_FILE_PATH: "strings"
  LOG_DIR: "logs"
  LOG_FILE: "logs.txt"
  LOG_LEVEL: "INFO"  # (DEBUG, INFO, WARNING, ERROR, CRITICAL)
  MAX_SIZE_MB: 10
  DEFAULT_LANGUAGE: "ru"
  ALLOWED_LANGUAGES: [ "ru", "en" ]
  TIMESTAMP_FORMAT: "%H:%M %d.%m.%Y"
  TIME_ZONE: "Europe/Moscow"
  PLUGINS:
    - IRIS:
        # Параметры доступа к серверам по умолчанию -------------------------------
        - URL_DEMO = https://superuser:SYS@appadmin.demo.community.intersystems.com/apptoolsrest/products/
        - CC_DEMO_USERViewLog = https://superuser:SYS@appadmin.demo.community.intersystems.com/apptoolsrest/custom-task/user/run&class=apptools.core.rest&met=GetLastLogs&par=5
prod:
  TELEGRAM_TOKEN:  "<121212-12121212>"
  DATABASE_URL: "postgres://postgres:postgres@localhost:5432/telebot"
  PLUGINS:
    - GITLAB:
        # gitlab.com -------------------------------
    - GIGA:
        - GIGA_CHAT = dfddfdfdfdiiijiiuuyiuyuh

dev:
  TELEGRAM_TOKEN: "<234344-121212343434312>"
  DATABASE_URL: "postgres://postgres:postgres@localhost:5432/telebot"
  PLUGINS:
    - IRIS:
        - URL_DEMO = https://superuser:Dev@appadmin.demo.community.intersystems.com/apptoolsrest/products/    # Демо
    - GITLAB:
        - ACCESS_TOKEN = glpat-sdfsdfsdfsdfsffs
        - GRAPHQL_URL = https://gitlab.com/api/graphql
        - GITLAB_URL = https://gitlab.com/api/v4/projects/23890341/issues
        - GITLAB_LABELS = Табель
        - PROJ_RU = Периметр,Ветер,Спектр
        - PROJ_EN = perimetr,wind,spectr
    - GIGA:
        - GIGA_CHAT = jhuhuihijmsdfswrddwwdw==
